
name: Test and Lint

on:
   workflow_call:
        secrets:
          DOCKERHUB_USER:
            required: true
            description: "Username for DockerHub auth"
          DOCKERHUB_TOKEN:
            required: true
            description: "Token for DockerHub auth"

jobs:
    python:
        name: Python
        runs-on: ubuntu-22.04
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Test
              run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Python flake8
              run: docker compose run --rm app sh -c "flake8"

    terraform:
      name: Terraform
      runs-on: ubuntu-22.04
      steps:
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout 
          uses: actions/checkout@v4
        - name: Terraform lint
          env:                                          # <--- checkear esto
            AWS_ACCESS_KEY_ID: dummy
            AWS_SECRET_ACCESS_KEY: dummy
            TF_WORKSPACE: default
            TF_VAR_db_password: dummy
            TF_VAR_ecr_proxy_image: dummy
            TF_VAR_ecr_app_image: dummy
            TF_VAR_django_secret_key: dummy      
          run: |
            cd infra/
            docker compose run --rm terraform -chdir=deploy/ init -backend=false
            docker compose run --rm terraform -chdir=setup/ init -backend=false
            docker compose run --rm terraform -chdir=setup/ validate 
            docker compose run --rm terraform -chdir=setup/ fmt -check
            docker compose run --rm terraform -chdir=deploy/ validate 
            docker compose run --rm terraform -chdir=deploy/ fmt -check
                   

